# Generated by Django 4.2.5 on 2023-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_mobile_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
